using System;
using UnityEngine;

namespace RootsDance.Environment
{
    /// <summary>
    /// The meshes a scene's MeshColliders use, with their convex flag, so they can be cooked on
    /// worker threads before the scene activates. Creating a MeshCollider cooks its mesh on the main
    /// thread unless cooked data is already cached — for Main Environment that was 172 cooks and 5.5
    /// seconds inside the activation frame. Generated by the Editor from the scene; a stale set only
    /// costs a few wasted cooks, never correctness, since the collider cooks anything missing itself.
    /// </summary>
    public sealed class CollisionPrebakeSet : ScriptableObject
    {
        [SerializeField] private Mesh[] m_meshes = Array.Empty<Mesh>();
        [SerializeField] private bool[] m_convex = Array.Empty<bool>();

        public Mesh[] Meshes => m_meshes;
        public bool[] Convex => m_convex;
        public int Count => m_meshes.Length;

        /// <summary>Editor baker entry point.</summary>
        public void Populate(Mesh[] meshes, bool[] convex)
        {
            if (meshes.Length != convex.Length)
            {
                throw new ArgumentException("Meshes and convex flags must have the same length.");
            }

            m_meshes = meshes;
            m_convex = convex;
        }
    }
}
