using System;
using UnityEngine;

namespace RootsDance.Environment
{
    /// <summary>
    /// A baked set of prop placements: a small table of prototype prefabs and, per item, which
    /// prototype goes where. Generated by the Editor baker from authored vegetation groups, spawned
    /// at runtime by <see cref="StreamedPlacementSpawner"/> a few hundred items per frame instead of
    /// all of them in the scene's load frame. Positions and rotations are world space; scales are the
    /// item's local scale under its group parent, exactly as authored.
    /// </summary>
    public sealed class StreamedPlacementSet : ScriptableObject
    {
        [Serializable]
        public struct Prototype
        {
            public GameObject Prefab;

            [Tooltip("True when the prefab carries colliders: its items are spawned only once the "
                + "collision meshes have been cooked off the main thread.")]
            public bool HasColliders;
        }

        [SerializeField] private Prototype[] m_prototypes = Array.Empty<Prototype>();

        [Tooltip("Path of each group's parent below the spawner's group root, e.g. 'ZoneE_Corridor1Ecology/PIN'.")]
        [SerializeField] private string[] m_groupParentPaths = Array.Empty<string>();

        [Tooltip("Name of the group object recreated under that parent, e.g. 'C00V_Group_ZoneE_Corridor1Ecology'.")]
        [SerializeField] private string[] m_groupNames = Array.Empty<string>();

        [SerializeField] private int[] m_prototypeIndices = Array.Empty<int>();
        [SerializeField] private int[] m_groupIndices = Array.Empty<int>();
        [SerializeField] private Vector3[] m_positions = Array.Empty<Vector3>();
        [SerializeField] private Quaternion[] m_rotations = Array.Empty<Quaternion>();
        [SerializeField] private Vector3[] m_scales = Array.Empty<Vector3>();

        [Tooltip("Every mesh a prototype's MeshCollider uses, with whether it is convex, so the "
            + "spawner can cook them on worker threads before the first collider is created.")]
        [SerializeField] private Mesh[] m_collisionMeshes = Array.Empty<Mesh>();
        [SerializeField] private bool[] m_collisionConvex = Array.Empty<bool>();

        public int ItemCount => m_prototypeIndices.Length;
        public Prototype[] Prototypes => m_prototypes;
        public string[] GroupParentPaths => m_groupParentPaths;
        public string[] GroupNames => m_groupNames;
        public int[] PrototypeIndices => m_prototypeIndices;
        public int[] GroupIndices => m_groupIndices;
        public Vector3[] Positions => m_positions;
        public Quaternion[] Rotations => m_rotations;
        public Vector3[] Scales => m_scales;
        public Mesh[] CollisionMeshes => m_collisionMeshes;
        public bool[] CollisionConvex => m_collisionConvex;

        /// <summary>Editor baker entry point; replaces every array in one go so the set is never half-written.</summary>
        public void Populate(Prototype[] prototypes, string[] groupParentPaths, string[] groupNames,
            int[] prototypeIndices, int[] groupIndices, Vector3[] positions, Quaternion[] rotations, Vector3[] scales,
            Mesh[] collisionMeshes, bool[] collisionConvex)
        {
            int n = prototypeIndices.Length;

            if (groupIndices.Length != n || positions.Length != n || rotations.Length != n || scales.Length != n)
            {
                throw new ArgumentException("Item arrays must all have the same length.");
            }

            if (groupParentPaths.Length != groupNames.Length || collisionMeshes.Length != collisionConvex.Length)
            {
                throw new ArgumentException("Paired arrays must have the same length.");
            }

            m_prototypes = prototypes;
            m_groupParentPaths = groupParentPaths;
            m_groupNames = groupNames;
            m_prototypeIndices = prototypeIndices;
            m_groupIndices = groupIndices;
            m_positions = positions;
            m_rotations = rotations;
            m_scales = scales;
            m_collisionMeshes = collisionMeshes;
            m_collisionConvex = collisionConvex;
        }
    }
}
